DROP TABLE IF EXISTS Transport;
DROP TABLE IF EXISTS DispatchNoteLine;
DROP TABLE IF EXISTS DispatchNote;
DROP TABLE IF EXISTS SalesOrderLine;
DROP TABLE IF EXISTS SalesOrder;
DROP TABLE IF EXISTS Stock;
DROP TABLE IF EXISTS WarehouseStockDefinition;
DROP TABLE IF EXISTS PriceHistory;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS PhysicalZone;
DROP TABLE IF EXISTS Warehouse;
DROP TABLE IF EXISTS Carrier;
DROP TABLE IF EXISTS GeographicZone;
GO